### ISSUE TITLE
Update save load system file in sync with tutorials on YouTube 

### ISSUE THREAD

**Issue by dragonemperor03** [shapedbyrainstudios/save-load-system#2]
Hey can you update this in sync with the tutorial, I’ve tried implementing it following the tutorial but not able to load the game after adding multiple slots, thank you

**Comment by shapedbyrainstudios** [comment]
Hey there! There are different branches that correspond to each tutorial video. Each _should_ be the exact code used for that tutorial. I push it directly after recording the videos footage.

For the Multiple Save Slots tutorial, ensure that you're looking at the '4-save-slots-implemented' branch - https://github.com/trevermock/save-load-system/tree/4-save-slots-implemented

I hope that helps! If you see some other sort of mismatch though, feel free to let me know and I'll take a closer look. :)
